<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ScheckParam extends Model
{
    use HasFactory;

    protected $table = 'scheck_params';

    protected $fillable = [
        'Vo',
        'S10',
        'S20',
        'S35',
        'S40',
        'S50',
        'S55',
        'S70',
        'S100',
        'Ke',
        'EB',
        'Eg',
        'Rg',
        'Ra',
        'Lg',
        'Bg',
        'Ba',
        'Ha',
        'Co',
        'phi',
        'C',
        'C1',
        'C2',
        'Fbtm',
        'Ftop',
        'wall_tie_stress',
        'wall_tie_stress2',
        'L10',
        'L20',
        'L35',
        'L40',
        'L50',
        'L55',
        'L70',
        'L100',
        'H10',
        'H20',
        'H35',
        'H40',
        'H50',
        'H55',
        'H70',
        'H100',
        'A10',
        'A20',
        'A35',
        'A40',
        'A50',
        'A55',
        'A70',
        'A100',
        'Vz10',
        'Vz20',
        'Vz35',
        'Vz40',
        'Vz50',
        'Vz55',
        'Vz70',
        'Vz100',
        'QzN10',
        'QzN20',
        'QzN35',
        'QzN40',
        'QzN50',
        'QzN55',
        'QzN70',
        'QzN100',
        'r',
        'Pbtm10',
        'Pbtm20',
        'Pbtm35',
        'Pbtm40',
        'Pbtm50',
        'Pbtm55',
        'Pbtm70',
        'Pbtm100',
        'Ptop10',
        'Ptop20',
        'Ptop35',
        'Ptop40',
        'Ptop50',
        'Ptop55',
        'Ptop70',
        'Ptop100',
        'Ltop',
        'htop1',
        'htop2',
        'atop1',
        'atop2',
        'War',
        // W上の値（各高さ範囲のA行）
        'Wup10',
        'Wup20',
        'Wup35',
        'Wup40',
        'Wup50',
        'Wup55',
        'Wup70',
        'Wup100',
        // W下の値（各高さ範囲のB行）
        'Wdn10',
        'Wdn20',
        'Wdn35',
        'Wdn40',
        'Wdn50',
        'Wdn55',
        'Wdn70',
        'Wdn100',
        // Ltop系列（各高さ範囲の幅）
        'Ltop10',
        'Ltop20',
        'Ltop35',
        'Ltop40',
        'Ltop50',
        'Ltop55',
        'Ltop70',
        'Ltop100',
        // Htopup系列（各高さ範囲の設定高さA）
        'Htopup10',
        'Htopup20',
        'Htopup35',
        'Htopup40',
        'Htopup50',
        'Htopup55',
        'Htopup70',
        'Htopup100',
        // Htopdn系列（各高さ範囲の設定高さB）
        'Htopdn10',
        'Htopdn20',
        'Htopdn35',
        'Htopdn40',
        'Htopdn50',
        'Htopdn55',
        'Htopdn70',
        'Htopdn100',
    ];
}
